### ISSUE TITLE
Not all 81 segments being avoided

### ISSUE THREAD

**Issue by samedelstein** [code-for-syracuse/without81#11]
I-81 would be replaced between about the SU exits and the 690 interchange. When I search directions from within Syracuse, many still put me onto I-81, which I think is in error.
![screen shot 2016-08-09 at 9 50 43 pm](https://cloud.githubusercontent.com/assets/5737320/17539349/6e788180-5e7b-11e6-9250-477b2768eb38.png)

**Comment by mheadd** [comment]
I can replicate this issue. Not sure why, but for address on the East side of 81, the API is routing via 81 regardless of the inclusion of segment IDs that must be avoided. Working on fixing it.

**Comment by mheadd** [comment]
@samedelstein This should be fixed now. Let me know if you continue to see this issue. Thanks!
