### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by DJViau** [code-for-syracuse/without81#16]
Mark,

I noticed two typos while reviewing the site.  

On the About page, in The arguments, in the Dig row, in the Against column, there's an instance of "disrutive" that should probably read "disruptive."

On the Contact page, there's an instance of "wwant" that should probably be "want."

Cool site; this is a classic Mark Headd project.  I'm looking forward to seeing more work from the Upstate Data Project.

Dan

**Comment by mheadd** [comment]
Thanks for catching these, @DJViau!
