### ISSUE TITLE
Address autocomplete?

### ISSUE THREAD

**Issue by mheadd** [code-for-syracuse/without81#7]
Might make it easier for users if the address entry fields used an autocomplete service, to ensure proper address entry for route calculation.

**Comment by samedelstein** [comment]
Mapquest doesn't recognize landmarks (Hancock International Airport) so autocomplete would be useful

**Comment by mheadd** [comment]
@samedelstein What I might do - instead of doing a full autocomplete - is simply create a (shortish) list of common landmarks, and use that in the input fields. This will make it way easier to implement, and help users going to or from one of these places.
